name = "SequentialOutputChannels"
uuid = "378a5cb6-73fb-4189-b384-0a829fc08157"
authors = ["Alberto Mengali <disberd@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.9"
Aqua = "0.8"
Test = "1"
Random = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"

[targets]
test = ["Test", "Random", "Aqua"]
